### ISSUE TITLE
DaggerContactsComponent class file is missing

### ISSUE THREAD

**Issue by prabhuk56** [abhaysood/BlrDroidDevfestDemo#1]
Hi,
  I got error while i am trying to run your source. But i got the following error,

**cannot find symbol : com.abhay23.blrdroiddevfestdemo.contacts_list.DaggerContactsComponent**

**Comment by abhaysood** [comment]
This is a class generated by Dagger. Just go ahead and build the project, you should be able to see it.

**Comment by prabhuk56** [comment]
Found the issue.
Its due missing `di` package at :

https://github.com/abhaysood/BlrDroidDevfestDemo/blob/master/app/src/main/java/com/abhay23/blrdroiddevfestdemo/di/DaggerInjector.java#L7

This could be due to your last commit https://github.com/abhaysood/BlrDroidDevfestDemo/commit/f52725322db6ce86ed7f8d49f6fe03f782334296
